# Generated by Django 5.2 on 2025-04-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "calificacion",
                    models.IntegerField(
                        choices=[
                            (1, "1 estrella"),
                            (2, "2 estrellas"),
                            (3, "3 estrellas"),
                            (4, "4 estrellas"),
                            (5, "5 estrellas"),
                        ]
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
