# Generated by Django 4.2.20 on 2025-04-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('carniceria', 'Carnicería'), ('fiambreria', 'Fiambrería'), ('salon', 'Salón'), ('caja', 'Caja')], max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('amabilidad', models.IntegerField()),
                ('eficiencia', models.IntegerField()),
                ('limpieza', models.IntegerField()),
                ('recordas_quien', models.CharField(blank=True, max_length=100)),
                ('destacado', models.TextField(blank=True)),
                ('como_conociste', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google', 'Google'), ('pantallas', 'Pantallas'), ('recomendacion', 'Recomendación')], max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
