# Generated by Django 5.2 on 2025-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="calificacion",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="comentario",
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comentario",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
