# Generated by Django 4.2.20 on 2025-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='recordas_quien',
            field=models.CharField(blank=True, choices=[('', 'Selecciona una opción'), ('empleado_1', 'Empleado 1'), ('empleado_2', 'Empleado 2'), ('empleado_3', 'Empleado 3')], max_length=100),
        ),
    ]
