# Generated by Django 4.2.20 on 2025-04-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comentario_recordas_quien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='recordas_quien',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
